
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Program_Bengkel_Motor extends javax.swing.JFrame {
    java.util.Date tglsekarang = new java.util.Date();
    private SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private String tanggal = smpdtfmt.format(tglsekarang);
    /**
     * Creates new form Program_Bengkel_Motor
     */
    public Program_Bengkel_Motor() {
        initComponents();
        //labeluser.setText(UserID.getUserLogin());
        setLocationRelativeTo(this);
        tgl.setText(tanggal);
        lbtgl.setText(tanggal);
        setJam();
    }
  
    
public final void setJam(){
ActionListener taskPerformer = new ActionListener() {

    @Override
public void actionPerformed(ActionEvent evt) {
String nol_jam = "", nol_menit = "",nol_detik = "";

java.util.Date dateTime = new java.util.Date();
int nilai_jam = dateTime.getHours();
int nilai_menit = dateTime.getMinutes();
int nilai_detik = dateTime.getSeconds();

if(nilai_jam <= 9) nol_jam= "0";
if(nilai_menit <= 9) nol_menit= "0";
if(nilai_detik <= 9) nol_detik= "0";

String jam = nol_jam + Integer.toString(nilai_jam);
String menit = nol_menit + Integer.toString(nilai_menit);
String detik = nol_detik + Integer.toString(nilai_detik);

lblwaktu.setText(jam+":"+menit+":"+detik+"");
}

};
new Timer(1000, taskPerformer).start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbfmmotor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbtempat = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        lblwaktu = new javax.swing.JLabel();
        lbnoserv = new javax.swing.JLabel();
        txtnoserv = new javax.swing.JTextField();
        lbnamacstm = new javax.swing.JLabel();
        txtnamacstm = new javax.swing.JTextField();
        lbalamat = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        lbnohp = new javax.swing.JLabel();
        txtnohp = new javax.swing.JTextField();
        lbmotor = new javax.swing.JLabel();
        txtmotor = new javax.swing.JTextField();
        lbnopol = new javax.swing.JLabel();
        txtnopol = new javax.swing.JTextField();
        lbmekanik = new javax.swing.JLabel();
        txtmekanik = new javax.swing.JTextField();
        lbket = new javax.swing.JLabel();
        cbserv = new javax.swing.JCheckBox();
        cbgantisp = new javax.swing.JCheckBox();
        lbsp = new javax.swing.JLabel();
        lbnamasp = new javax.swing.JLabel();
        txtnamasp = new javax.swing.JTextField();
        lbharga = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        lbbanyak = new javax.swing.JLabel();
        txtbanyak = new javax.swing.JTextField();
        btnTambahkan = new javax.swing.JButton();
        btnTambahBaru = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBersihkan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblsp = new javax.swing.JTable();
        lbjmlbar = new javax.swing.JLabel();
        txtjmlbar = new javax.swing.JTextField();
        lbtotal = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        lbrincian = new javax.swing.JLabel();
        lbbiayaserv = new javax.swing.JLabel();
        txtbiayaserv = new javax.swing.JTextField();
        lbgantisp = new javax.swing.JLabel();
        txtgantisp = new javax.swing.JTextField();
        lbtotalakhir = new javax.swing.JLabel();
        txttotalakhir = new javax.swing.JTextField();
        lbtglmasuk = new javax.swing.JLabel();
        lbtgl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txthasil = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 13, 76));

        lbfmmotor.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 24)); // NOI18N
        lbfmmotor.setForeground(new java.awt.Color(255, 255, 255));
        lbfmmotor.setText("FM MOTOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(lbfmmotor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbfmmotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 530, 60));

        jPanel2.setBackground(new java.awt.Color(13, 13, 76));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1040, 20));

        jPanel3.setBackground(new java.awt.Color(13, 13, 76));

        lbtempat.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbtempat.setForeground(new java.awt.Color(255, 255, 255));
        lbtempat.setText("Jl. Banjarsari, Tembalang, Semarang");

        tgl.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        tgl.setText(" ");

        lblwaktu.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        lblwaktu.setForeground(new java.awt.Color(255, 255, 255));
        lblwaktu.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblwaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbtempat, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbtempat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl)
                    .addComponent(lblwaktu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 500, 60));

        lbnoserv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbnoserv.setText("No. Service");
        getContentPane().add(lbnoserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 85, 102, 20));

        txtnoserv.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtnoserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 85, 384, -1));

        lbnamacstm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbnamacstm.setText("Nama Customer");
        getContentPane().add(lbnamacstm, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 116, 102, 20));

        txtnamacstm.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtnamacstm, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 116, 384, -1));

        lbalamat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbalamat.setText("Alamat");
        getContentPane().add(lbalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 147, 102, 20));

        txtalamat.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 147, 384, -1));

        lbnohp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbnohp.setText("No. HP");
        getContentPane().add(lbnohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 179, 102, 20));

        txtnohp.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtnohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 179, 384, -1));

        lbmotor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbmotor.setText("Motor");
        getContentPane().add(lbmotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 213, 102, -1));

        txtmotor.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtmotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 210, 151, -1));

        lbnopol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbnopol.setText("Nomor Polisi");
        getContentPane().add(lbnopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 213, 72, -1));

        txtnopol.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtnopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 131, -1));

        lbmekanik.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbmekanik.setText("Mekanik");
        getContentPane().add(lbmekanik, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 241, 102, 17));

        txtmekanik.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtmekanik, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 241, 384, -1));

        lbket.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbket.setText("Keterangan");
        getContentPane().add(lbket, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 288, 102, 17));

        cbserv.setBackground(new java.awt.Color(225, 225, 235));
        cbserv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbserv.setText("Service");
        cbserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbservActionPerformed(evt);
            }
        });
        getContentPane().add(cbserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 285, 101, -1));

        cbgantisp.setBackground(new java.awt.Color(225, 225, 235));
        cbgantisp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbgantisp.setText("Ganti Sparepart");
        cbgantisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgantispActionPerformed(evt);
            }
        });
        getContentPane().add(cbgantisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 285, -1, -1));

        lbsp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbsp.setText("Sparepart :");
        getContentPane().add(lbsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 111, -1));

        lbnamasp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbnamasp.setText("Nama Sparepart");
        getContentPane().add(lbnamasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 120, 20));

        txtnamasp.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtnamasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 279, -1));

        lbharga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbharga.setText("Harga");
        getContentPane().add(lbharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 120, 20));

        txtharga.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 279, -1));

        lbbanyak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbbanyak.setText("Banyak");
        getContentPane().add(lbbanyak, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 120, 20));

        txtbanyak.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtbanyak, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 279, -1));

        btnTambahkan.setBackground(new java.awt.Color(11, 11, 28));
        btnTambahkan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTambahkan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahkan.setText("Tambahkan");
        btnTambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahkanActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        btnTambahBaru.setBackground(new java.awt.Color(11, 11, 28));
        btnTambahBaru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTambahBaru.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahBaru.setText("Tambah Baru");
        btnTambahBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBaruActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        btnHapus.setBackground(new java.awt.Color(11, 11, 28));
        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(11, 11, 28));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, -1));

        btnBersihkan.setBackground(new java.awt.Color(11, 11, 28));
        btnBersihkan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBersihkan.setForeground(new java.awt.Color(255, 255, 255));
        btnBersihkan.setText("Bersihkan");
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });
        getContentPane().add(btnBersihkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 300, -1, -1));

        tblsp.setBackground(new java.awt.Color(192, 192, 208));
        tblsp.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblsp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Banyak", "Nama Sparepart", "Harga", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsp.setShowHorizontalLines(false);
        jScrollPane3.setViewportView(tblsp);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 85, 480, 170));

        lbjmlbar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbjmlbar.setText("Jumlah Barang:");
        getContentPane().add(lbjmlbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 88, 20));

        txtjmlbar.setBackground(new java.awt.Color(225, 225, 235));
        txtjmlbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlbarActionPerformed(evt);
            }
        });
        getContentPane().add(txtjmlbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 40, 25));

        lbtotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbtotal.setText("Total Harga:");
        getContentPane().add(lbtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, 70, 20));

        txttotal.setEditable(false);
        txttotal.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 260, 120, 25));

        lbrincian.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbrincian.setText("Rincian Biaya:");
        getContentPane().add(lbrincian, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 171, -1));

        lbbiayaserv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbbiayaserv.setText("Biaya Servis:");
        getContentPane().add(lbbiayaserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 358, 84, 20));

        txtbiayaserv.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtbiayaserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 110, -1));

        lbgantisp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbgantisp.setText("Biaya Ganti Sparepart:");
        getContentPane().add(lbgantisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 384, 132, 30));

        txtgantisp.setBackground(new java.awt.Color(225, 225, 235));
        getContentPane().add(txtgantisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 117, -1));

        lbtotalakhir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbtotalakhir.setText("Total Biaya yang Harus Dibayar:");
        getContentPane().add(lbtotalakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 210, -1));

        txttotalakhir.setEditable(false);
        txttotalakhir.setBackground(new java.awt.Color(225, 225, 235));
        txttotalakhir.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        getContentPane().add(txttotalakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 441, 184, 40));

        lbtglmasuk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbtglmasuk.setText("Tanggal Masuk :");
        getContentPane().add(lbtglmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, -1, -1));

        lbtgl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbtgl.setText(" ");
        getContentPane().add(lbtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, 89, -1));

        txthasil.setBackground(new java.awt.Color(225, 225, 235));
        txthasil.setColumns(20);
        txthasil.setRows(5);
        jScrollPane1.setViewportView(txthasil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1000, 130));

        jLabel1.setBackground(new java.awt.Color(58, 58, 86));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noeng/img/taa.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1035, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbservActionPerformed
        // TODO add your handling code here:
        if (cbserv.isSelected() == true){
            txtbiayaserv.setEditable(true);
        }else{
            txtbiayaserv.setEditable(true);
            txtbiayaserv.setText("");
        }
    }//GEN-LAST:event_cbservActionPerformed
    
    private void cbgantispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgantispActionPerformed
        // TODO add your handling code here:
        if (cbgantisp.isSelected() == true){
            txtgantisp.setEditable(true);
        }else{
            txtgantisp.setEditable(true);
            txtgantisp.setText("");
        }        
    }//GEN-LAST:event_cbgantispActionPerformed

    private void btnTambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahkanActionPerformed
        // TODO add your handling code here:
        try{
           
            txtnamasp.getText();
            txtharga.getText();
            txtbanyak.getText();
            
            
            int banyak = Integer.parseInt(txtbanyak.getText());
            int harga = Integer.parseInt(txtharga.getText());
            int jumlah = (banyak*harga);
            int jmlbar = 0;        
            DefaultTableModel model= (DefaultTableModel) tblsp.getModel();

            model.addRow(new Object[]{txtbanyak.getText(),txtnamasp.getText(),txtharga.getText(),jumlah});

            int total = 0;
            for (int i=0; i<tblsp.getRowCount(); i++){
                int amount0 = Integer.parseInt(tblsp.getValueAt(i,0).toString());
                int amount = Integer.parseInt(tblsp.getValueAt(i,3).toString());
            jmlbar = jmlbar + amount0;
            total = total+ amount;
            txttotal.setText(String.valueOf(total));
            txtjmlbar.setText(String.valueOf(jmlbar));
            }
        }catch (Exception ex)
        {    
            JOptionPane.showMessageDialog(this, "Data harga dan banyak harus berupa angka!", "Peringatan!!", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnTambahkanActionPerformed

    private void btnTambahBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBaruActionPerformed
        // TODO add your handling code here:
        txtnamasp.setText("");
        txtharga.setText("");
        txtbanyak.setText("");
        txtnamasp.requestFocus();
    }//GEN-LAST:event_btnTambahBaruActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)tblsp.getModel();
        
        try{
            int SelectedRowIndex=
            tblsp.getSelectedRow();
            model.removeRow(SelectedRowIndex);
            int jmlbar = 0;
            int total = 0;
            
            for (int i=0; i<tblsp.getRowCount(); i++){
                int amount0 = Integer.parseInt(tblsp.getValueAt(i,0).toString());
                int amount = Integer.parseInt(tblsp.getValueAt(i,3).toString());
                jmlbar = jmlbar + amount0;
                total = total+ amount;
        }
        txttotal.setText(String.valueOf(total)); 
        txtjmlbar.setText(String.valueOf(jmlbar));
        }catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Tidak ada data yang Anda pilih!", "Peringatan!!", JOptionPane.WARNING_MESSAGE);     
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try{

            String totalharga = txttotal.getText();
            int totalhargasp = Integer.parseInt(totalharga);
            int biaya1 = 0;
            int biaya2 = 0;
            if (cbserv.isSelected()){
            biaya1 = biaya1 + 40000;    
            }
            txtbiayaserv.setText(""+biaya1);
        
        
            if (cbgantisp.isSelected()){
            String jmlbar = txtjmlbar.getText();
            int gantisp = Integer.parseInt(jmlbar);
            gantisp = gantisp*10000;
            biaya2 = biaya2 + gantisp;                   
            }
            txtgantisp.setText(""+biaya2);
        
            int totalakhir = 0;
            totalakhir = biaya1 + biaya2 + totalhargasp;
            txttotalakhir.setText(""+totalakhir);
            
            txthasil.append("No. Servis : " +txtnoserv.getText()+
                "\nNama Customer : " +txtnamacstm.getText()+
                "\nAlamat : " +txtalamat.getText()+
                "\nNo. HP : " +txtnohp.getText()+
                "\nMotor : " +txtmotor.getText() + "Nomor Polisi : " +txtnopol.getText()+
                "\nMekanik : " +txtmekanik.getText()+
                "\nRincian Pembayaran : - Biaya Servis : " +txtbiayaserv.getText()+
                " // - Biaya Ganti Sparepart : " +txtgantisp.getText()+
                " // - Total Harga Sparepart : " +txttotal.getText()+
                "\nTotal Biaya yang Harus Dibayar : " +txttotalakhir.getText()+
                "\nTanggal Masuk : " +lbtgl.getText());
        
        }catch (Exception ex)
        
        {
            JOptionPane.showMessageDialog(this, "Anda belum menambahkan data sparepart!", "Peringatan!!", JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda ingin menghapus semua data?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
        
        DefaultTableModel model=(DefaultTableModel)tblsp.getModel();
        try{
        while (model.getRowCount()>0){
            for (int i=0; i<model.getRowCount(); ++i){
                model.removeRow(i);    
            }
        }
        
        txtnoserv.setText("");
        txtnamacstm.setText("");
        txtalamat.setText("");
        txtnohp.setText("");
        txtmotor.setText("");
        txtnopol.setText("");
        txtmekanik.setText("");
        cbserv.setSelected(false);
        cbgantisp.setSelected(false);
        txtnamasp.setText("");
        txtharga.setText("");
        txtbanyak.setText("");
        txtjmlbar.setText("");
        txttotal.setText("");
        txtbiayaserv.setText("");
        txtgantisp.setText("");
        txttotalakhir.setText("");
        txtnoserv.requestFocus();
              
        
        }catch (Exception ex)
        {
    }
        }
        
    }//GEN-LAST:event_btnBersihkanActionPerformed

    private void txtjmlbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlbarActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program_Bengkel_Motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program_Bengkel_Motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program_Bengkel_Motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program_Bengkel_Motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program_Bengkel_Motor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahBaru;
    private javax.swing.JButton btnTambahkan;
    private javax.swing.JCheckBox cbgantisp;
    private javax.swing.JCheckBox cbserv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbalamat;
    private javax.swing.JLabel lbbanyak;
    private javax.swing.JLabel lbbiayaserv;
    private javax.swing.JLabel lbfmmotor;
    private javax.swing.JLabel lbgantisp;
    private javax.swing.JLabel lbharga;
    private javax.swing.JLabel lbjmlbar;
    private javax.swing.JLabel lbket;
    private javax.swing.JLabel lblwaktu;
    private javax.swing.JLabel lbmekanik;
    private javax.swing.JLabel lbmotor;
    private javax.swing.JLabel lbnamacstm;
    private javax.swing.JLabel lbnamasp;
    private javax.swing.JLabel lbnohp;
    private javax.swing.JLabel lbnopol;
    private javax.swing.JLabel lbnoserv;
    private javax.swing.JLabel lbrincian;
    private javax.swing.JLabel lbsp;
    private javax.swing.JLabel lbtempat;
    private javax.swing.JLabel lbtgl;
    private javax.swing.JLabel lbtglmasuk;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JLabel lbtotalakhir;
    private javax.swing.JTable tblsp;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtbanyak;
    private javax.swing.JTextField txtbiayaserv;
    private javax.swing.JTextField txtgantisp;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextArea txthasil;
    private javax.swing.JTextField txtjmlbar;
    private javax.swing.JTextField txtmekanik;
    private javax.swing.JTextField txtmotor;
    private javax.swing.JTextField txtnamacstm;
    private javax.swing.JTextField txtnamasp;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JTextField txtnopol;
    private javax.swing.JTextField txtnoserv;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotalakhir;
    // End of variables declaration//GEN-END:variables
}
